apiVersion: v1
kind: Pod
metadata:
  name: simpleapp
  labels:
    name: simpleapp
spec:
  containers:
  - name: simpleapp
    image: jorgeandrealves/simpleapp:latest
    resources:
      limits:
        memory: "68Mi"
        cpu: "50m"
    ports:
      - containerPort: 5000
